import SwiftUI

/// The web app's colour tokens, one colour set per token with light and dark
/// appearances. Generated by `scripts/sync-theme.py` from
/// `north-web-app/web/assets/css/input.css`; edit the CSS, not the catalog.
///
/// Prefer system materials and semantic colours (`.primary`, `.secondary`,
/// grouped backgrounds) for chrome so the app feels native, and reach for these
/// where the brand speaks: the coach, training sports, highlights.
public enum NorthColor {
    public static let background = named("Background")
    public static let foreground = named("Foreground")
    public static let card = named("Card")
    public static let cardForeground = named("CardForeground")
    public static let primary = named("Primary")
    public static let primaryForeground = named("PrimaryForeground")
    public static let secondary = named("Secondary")
    public static let secondaryForeground = named("SecondaryForeground")
    public static let muted = named("Muted")
    public static let mutedForeground = named("MutedForeground")
    public static let destructive = named("Destructive")
    public static let border = named("Border")
    public static let ring = named("Ring")
    public static let surface = named("Surface")
    public static let hairline = named("Hairline")

    /// Highlights and links: the web's `--north-signal`.
    public static let signal = named("Signal")
    /// Anything the coach says or does: the web's `--north-agent`.
    public static let agent = named("Agent")
    /// Warmth and streaks: the web's `--north-ember`.
    public static let ember = named("Ember")

    public enum Sport {
        public static let run = named("SportRun")
        public static let ride = named("SportRide")
        public static let swim = named("SportSwim")
        public static let walk = named("SportWalk")
        public static let strength = named("SportStrength")
        public static let other = named("SportOther")
    }

    private static func named(_ name: String) -> Color {
        Color(name, bundle: .module)
    }
}

/// Corner radii matching the web's `--radius: 0.65rem`.
public enum NorthRadius {
    public static let small: CGFloat = 6
    public static let medium: CGFloat = 10
    public static let large: CGFloat = 16
}
